// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEBg9vQf2XJ4gVaP5yJvTVj2C7AQVEj_s',
    appId: '1:412763203883:android:6a7076ab4c607a45423d6e',
    messagingSenderId: '412763203883',
    projectId: 'flutterkurstodo',
    storageBucket: 'flutterkurstodo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6D3hAIGuyGUoBndNdSb1wrbhDHPyajPw',
    appId: '1:412763203883:ios:ca211ef561e3e93b423d6e',
    messagingSenderId: '412763203883',
    projectId: 'flutterkurstodo',
    storageBucket: 'flutterkurstodo.appspot.com',
    androidClientId: '412763203883-r06on0rqepd35qks06fp451gm3mpq8oc.apps.googleusercontent.com',
    iosClientId: '412763203883-fvkis5ur3erfc8548e0q5rposk64f7c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
